### ISSUE TITLE
About LiveArea icons.

### ISSUE THREAD

**Issue by nkrapivin** [xerpi/vitastick#12]
Please sorry, I have bad art grades at school. I tried my best.

https://i.imgur.com/FR0alF1.jpg

https://i.imgur.com/NrrUgkq.jpg

**Comment by xerpi** [comment]
They are actually very nice! Mind uploading the png somewhere?

**Comment by nkrapivin** [comment]
Maybe do a pull request?
(srsly that stolen from vitashell design looks nice....)

**Comment by xerpi** [comment]
Oh yeah, that will work too :)

**Comment by nkrapivin** [comment]
Also I know about that red spots at startup png, I will fixed these, making pull request.
