### ISSUE TITLE
Throwing the USB in on a throws up Content Manager

### ISSUE THREAD

**Issue by Scrxtchy** [xerpi/vitastick#2]
Unsure what exactly goes on.
I have the skprx in my ux0:/tai/ folder along with a few other plugins, (adrenaline, Framecounter)
it's added to the KERNEL block, and I have rebooted a few times

Launching the VPK gives me a black screen, and plugging in the USB opens up the content manager warnings

**Comment by KawaiiAurora** [comment]
Would you mind posting your 'config.txt'?

**Comment by Scrxtchy** [comment]
```
# You must reboot for changes to take place.
*KERNEL
ux0:pspemu/adrenaline/adrenaline.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
# main is a special titleid for SceShell
ux0:app/MLCL00001/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ux0:app/MLCL00001/henkaku.suprx
*NPEZ00104
vs0:sys/external/libpgf.suprx
ux0:pspemu/adrenaline/adrenaline.suprx
*!main
*!VITASHELL
*ALL
ux0:tai/Framecounter.suprx
*KERNEL
ux0:tai/vitastick.skprx
```

I've also tried a variant with it underneath the initial KERNEL block (sharing with adrenaline) instead of being appended to the bottom of the file

**Comment by xerpi** [comment]
Well that's really weird, I guess you are using a regular PSVita and not a PSTV one?

**Comment by Scrxtchy** [comment]
Yeah, it's the PCH-1102 model as well

**Comment by xerpi** [comment]
Could you tryi disabling all the other plugins to see if they are causing conflict?

**Comment by Scrxtchy** [comment]
Never expected a conflict, Disabled the frame counter and it started working. Thanks
