### ISSUE TITLE
Error C2-12828-1

### ISSUE THREAD

**Issue by masterrite** [xerpi/vitastick#6]
Got this error on windows 10. Here's the psp2dmp file (I changed the extension to txt for uploading).

Thanks!

[psp2core-1498316649-0x00013828c3-eboot.bin.txt](https://github.com/xerpi/vitastick/files/1099840/psp2core-1498316649-0x00013828c3-eboot.bin.txt)

**Comment by xerpi** [comment]
Make sure the skprx is loaded before starting the vpk.

**Comment by masterrite** [comment]
It is loaded, on my fourth line in the config.txt:
`# You must reboot for changes to take place.
*KERNEL
ux0:adrenaline/adrenaline.skprx
ux0:tai/vitastick.skprx`
