### ISSUE TITLE
Not works on 3.65 enso firmware

### ISSUE THREAD

**Issue by nkrapivin** [xerpi/vitastick#9]
It's connecting, but any buttons I press have no effect. And no "errors" in debug log ;(

windows 7 x64.

**Comment by nkrapivin** [comment]
fixed with building from source. Also you forgot to put one line, without that, you will be unable to build vitastick.

**Comment by ckonr** [comment]
@nkrapivin what does building from source mean? its not working for me either and i am new to this

**Comment by nkrapivin** [comment]
Don't worry, I will write build instruction.

**Comment by ckonr** [comment]
@nkrapivin thank you, looking forward to it

**Comment by nkrapivin** [comment]
ok, tommorow i will make a pull request w/ Building section.

**Comment by nkrapivin** [comment]
@ckonr try this build https://drive.google.com/file/d/1agfMOzupjwavbaQS-DL-_TuW99nZ0qQ2/view?usp=sharing

**Comment by ckonr** [comment]
@nkrapivin still nothing. can you guide me through from step 1 on how and what to install? i am so lost. i am pressing all kinds of buttons but nothing works :(

**Comment by nkrapivin** [comment]
Please send me your ux0:tai/config.txt (or ur0, if you installed plugin to ur0)

**Comment by nkrapivin** [comment]
https://i.imgur.com/jYi1bvo.png
https://i.imgur.com/CmcVD1b.png
Here I am holding all buttons (I can) and it works for me.

**Comment by ckonr** [comment]
@nkrapivin https://drive.google.com/file/d/1rHFIi3KeH64rlc_xw5gz5Y9YTPT1d9YX/view?usp=sharing

**Comment by nkrapivin** [comment]
Hmm, looks good. I will send you debug build, no need to reinstall vpk, skprx only.

**Comment by ckonr** [comment]
@nkrapivin thank you. should i just simply replace the skprx file with the one you are sending?

**Comment by nkrapivin** [comment]
@ckonr yes, https://drive.google.com/file/d/1sYvSAvWyCJb9t6TBf1Dve3xGMwl8SotQ/view?usp=sharing
Then, replace the file, reboot your vita, launch VitaStick, connect vita to pc, try pressing some buttons, then send me ux0:dump/vitastick.txt file. This is the debug log.

**Comment by ckonr** [comment]
@nkrapivin i cannot see the folder "dump" in ux0

**Comment by nkrapivin** [comment]
then create it, reboot vita and try again

**Comment by ckonr** [comment]
@nkrapivin https://drive.google.com/file/d/1WSw4dPYJ0wm1lIniYGfNyF_EWW_OZ8YM/view?usp=sharing

**Comment by nkrapivin** [comment]
No errors, like mine problem. In what PC you are connecting Vita? Can you try to open USB-gamepad setup menu. (just search in Start menu "usb-" you will find usb-gamepads setup menu) just in case, what if buttons are working.

**Comment by ckonr** [comment]
I'm opening it with Asus RG56JR, on windows 10 http://prntscr.com/kaild3 this is what I get when i am trying to press ANY buttons

**Comment by nkrapivin** [comment]
No reaction? Can you please say your firmware version and vita model? (because I don't know what's wrong, sorry)

**Comment by ckonr** [comment]
@nkrapivin correct, 0 reaction, the Buttons 1-16 don't change colors. 3.65 henkaku enso. fat/oled model

**Comment by nkrapivin** [comment]
same (pch-1008 russia, 3.65 enso). Sorry, I don't know what's wrong.

**Comment by ckonr** [comment]
@nkrapivin maybe I don't have any buttons set up? I was trying to change what button does what but i could not find the file for it

**Comment by nkrapivin** [comment]
Of course, everything is hard-coded in plugin

**Comment by ckonr** [comment]
strange, i must be missing something then but i have no idea what it could be either.

**Comment by nkrapivin** [comment]
@xerpi help him please. I don't know what's wrong.

**Comment by xerpi** [comment]
@ckonr Try using the debug build skprx, then open the VPK, exit and you should see a file called `ux0:dump/vitastick.txt`.

**Comment by xerpi** [comment]
@ckonr Oh I see, everything looks right, can you try the latest version? https://github.com/xerpi/vitastick/releases

**Comment by ckonr** [comment]
@xerpi Seems to be working flawlessly. Thank you so much! (Mind if I ask you where I can find the controls? haha)

**Comment by nkrapivin** [comment]
@ckonr please close this issue

**Comment by nkrapivin** [comment]
Sorry! Just noticed that it was my issue!
